In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib

# 행(row) 다 보기
pd.set_option('display.max_rows', None)

# 열(column) 다 보기
pd.set_option('display.max_columns', None)

In [3]:
from PublicDataReader import Ecos
service_key = "2G5XUDEN750MGRZM37GF"
api = Ecos(service_key)
df = api.get_statistic_table_list()
df[df['통계명'] == '환율']

Empty DataFrame
Columns: [상위통계표코드, 통계표코드, 통계명, 시점, 검색가능여부, 출처]
Index: []

In [4]:
df[df['통계표코드'] == '901Y011']

Empty DataFrame
Columns: [상위통계표코드, 통계표코드, 통계명, 시점, 검색가능여부, 출처]
Index: []

In [7]:
display(df)

,상위통계표코드,통계표코드,통계명,시점,검색가능여부,출처
0,*,0000000001,1. 통화/금융,None,N,None
1,0000000001,0000000620,1.1. 통화/유동성(신지표),None,N,None
2,0000000620,0000000621,1.1.1. 본원통화,None,N,None
3,0000000621,0000000622,1.1.1.1. 본원통화 구성내역,None,N,None
4,0000000622,102Y004,"1.1.1.1.1. 본원통화 구성내역(평잔, 계절조정계열)",M,Y,None
5,0000000622,102Y002,"1.1.1.1.2. 본원통화 구성내역(평잔, 원계열)",M,Y,None
6,0000000622,102Y003,"1.1.1.1.3. 본원통화 구성내역(말잔, 계절조정계열)",M,Y,None
7,0000000622,102Y001,"1.1.1.1.4. 본원통화 구성내역(말잔, 원계열)",M,Y,한국은행
8,0000000620,0000000623,1.1.2. M1(협의통화),None,N,None
9,0000000623,0000000624,1.1.2.1. M1(협의통화) 상품별 구성내역,None,N,None
10,0000000624,161Y001,"1.1.2.1.1. M1 상품별 구성내역(평잔, 계절조정계열)",M,Y,None
11,0000000624,161Y002,"1.1.2.1.2. M1 상품별 구성내역(평잔, 원계열)",M,Y,None
12,0000000624,161Y003,"1.1.2.1.3. M1 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
13,0000000624,161Y004,"1.1.2.1.4. M1 상품별 구성내역(말잔, 원계열)",M,Y,None
14,0000000620,0000000625,1.1.3. M2(광의통화),None,N,None
15,0000000625,0000000626,1.1.3.1. M2(광의통화) 상품별 구성내역,None,N,None
16,0000000626,161Y005,"1.1.3.1.1. M2 상품별 구성내역(평잔, 계절조정계열)",M,Y,None
17,0000000626,161Y006,"1.1.3.1.2. M2 상품별 구성내역(평잔, 원계열)",M,Y,None
18,0000000626,161Y007,"1.1.3.1.3. M2 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
19,0000000626,161Y008,"1.1.3.1.4. M2 상품별 구성내역(말잔, 원계열)",M,Y,None
20,0000000625,0000000627,1.1.3.2. M2(광의통화) 경제주체별 보유현황,None,N,None
21,0000000627,161Y009,"1.1.3.2.1. M2 경제주체별 보유현황(평잔, 계절조정계열)",M,Y,None
22,0000000627,161Y010,"1.1.3.2.2. M2 경제주체별 보유현황(평잔, 원계열)",M,Y,None
23,0000000627,161Y011,"1.1.3.2.3. M2 경제주체별 보유현황(말잔, 계절조정계열)",M,Y,None
24,0000000627,161Y012,"1.1.3.2.4. M2 경제주체별 보유현황(말잔, 원계열)",M,Y,None
25,0000000625,0000000628,1.1.3.3. M2 기관별 구성내역,None,N,None
26,0000000628,161Y013,1.1.3.3.1. M2 기관별 구성내역(평잔),M,Y,None
27,0000000628,161Y014,1.1.3.3.2. M2 기관별 구성내역(말잔),M,Y,None
28,0000000620,0000000629,1.1.4. Lf(금융기관 유동성),None,N,None
29,0000000629,0000000630,1.1.4.1. Lf(금융기관 유동성) 구성내역,None,N,None
30,0000000630,171Y003,"1.1.4.1.1. Lf 구성내역(평잔, 계절조정계열)",M,Y,None
31,0000000630,171Y004,"1.1.4.1.2. Lf 구성내역(평잔, 원계열)",M,Y,None
32,0000000630,171Y001,"1.1.4.1.3. Lf 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
33,0000000630,171Y002,"1.1.4.1.4. Lf 상품별 구성내역(말잔, 원계열)",M,Y,None
34,0000000620,0000000631,1.1.5. L(광의유동성),None,N,None
35,0000000631,172Y001,"1.1.5.1. L(광의유동성) 구성내역(말잔, 계절조정계열)",M,Y,None
36,0000000631,172Y002,"1.1.5.2. L(광의유동성) 구성내역(말잔, 원계열)",M,Y,None
37,0000000620,0000000632,1.1.6. 예금취급기관 개관표,None,N,None
38,0000000632,161Y015,1.1.6.1. 예금취급기관 개관표(말잔),M,Y,None
39,0000000632,161Y016,1.1.6.2. 중앙은행 개관표(말잔),M,Y,None
40,0000000632,161Y017,1.1.6.3. 기타예금취급기관 개관표(말잔),M,Y,None
41,0000000001,0000000020,1.2. 금융기관 여수신,None,N,None
42,0000000020,0000000021,1.2.1. 수신,None,N,None
43,0000000021,0000000022,1.2.1.1. 예금은행 수신,None,N,None
44,0000000022,104Y014,1.2.1.1.1. 예금은행 총수신(평잔),M,Y,None
45,0000000022,104Y013,1.2.1.1.2. 예금은행 총수신(말잔),M,Y,None
46,0000000022,104Y008,"1.2.1.1.3. 예금은행 원화예금(종별, 평잔)",M,Y,None
47,0000000022,104Y015,"1.2.1.1.4. 예금은행 원화예금(종별, 말잔)",M,Y,한국은행
48,0000000022,104Y009,"1.2.1.1.5. 예금은행 원화예금(예금주별,말잔)",M,Y,None
49,0000000022,104Y010,"1.2.1.1.6. 예금은행 정기예금(기간별, 말잔)",M,Y,None
50,0000000021,0000000023,1.2.1.2. 비은행금융기관 수신,None,N,None
51,0000000023,111Y008,1.2.1.2.1. 비은행금융기관 수신(평잔),M,Y,None
52,0000000023,111Y007,1.2.1.2.2. 비은행금융기관 수신(말잔),M,Y,None
53,0000000020,0000000024,1.2.2. 여신,None,N,None
54,0000000024,104Y016,1.2.2.1. 예금은행 대출금(말잔),M,Y,None
55,0000000024,111Y009,1.2.2.2. 비은행금융기관 여신(말잔),M,Y,None
56,0000000020,0000000027,1.2.3. 지역별 여수신,None,N,None
57,0000000027,141Y002,1.2.3.1. 예금은행 지역별 수신(말잔),M,Y,None
58,0000000027,141Y006,1.2.3.2. 비은행예금취급기관 지역별 수신(말잔),M,Y,None
59,0000000027,141Y008,1.2.3.3. 생명보험회사 지역별 수신(말잔),M,Y,한국은행
60,0000000027,0000000031,1.2.3.4. 예금은행 지역별 대출금(말잔),None,N,None
61,0000000031,141Y003,1.2.3.4.1. 예금은행 지역별 대출금(말잔),M,Y,None
62,0000000031,151Y003,1.2.3.4.2. 예금은행 지역별 가계대출(말잔),M,Y,None
63,0000000031,141Y004,1.2.3.4.3. 예금은행 지역별 기업대출(말잔),M,Y,None
64,0000000027,0000000032,1.2.3.5. 비은행예금취급기관 지역별 여신(말잔),None,N,None
65,0000000032,141Y007,1.2.3.5.1. 비은행예금취급기관 지역별 여신(말잔),M,Y,None
66,0000000032,151Y006,1.2.3.5.2. 비은행예금취급기관 지역별 가계대출(말잔),M,Y,None
67,0000000032,141Y010,1.2.3.5.3. 비은행예금취급기관 지역별 기업대출(말잔),M,Y,None
68,0000000027,141Y009,1.2.3.6. 생명보험회사 지역별 여신(말잔),M,Y,한국은행
69,0000000027,141Y005,1.2.3.7. 예금은행 지역별 연체율,M,Y,None
70,0000000020,0000000035,1.2.4. 가계신용,None,N,None
71,0000000035,0000000036,1.2.4.1. 가계신용(분기),None,N,None
72,0000000036,151Y001,"1.2.4.1.1. 가계신용(업권별, 분기)",Q,Y,None
73,0000000036,151Y004,"1.2.4.1.2. 가계신용(용도별, 분기)",Q,Y,None
74,0000000035,0000000037,1.2.4.2. 예금취급기관 가계대출(월),None,N,None
75,0000000037,151Y002,"1.2.4.2.1. 예금취급기관 가계대출(업권별, 월)",M,Y,None
76,0000000037,151Y005,"1.2.4.2.2. 예금취급기관 가계대출(용도별, 월)",M,Y,None
77,0000000020,0000000038,1.2.5. 산업별대출금,None,N,None
78,0000000038,0000000039,1.2.5.1. 예금취급기관 산업별대출금,None,N,None
79,0000000039,131Y016,"1.2.5.1.1. 산업별대출금(예금취급기관, 전산업)",Q,Y,None
80,0000000039,131Y017,"1.2.5.1.2. 산업별대출금(예금취급기관, 용도별)",Q,Y,None
81,0000000038,0000000040,1.2.5.2. 예금은행 산업별대출금,None,N,None
82,0000000040,131Y013,"1.2.5.2.1. 산업별대출금(예금은행, 전산업)",Q,Y,None
83,0000000040,131Y011,"1.2.5.2.2. 산업별대출금(예금은행, 용도별)",Q,Y,None
84,0000000040,131Y010,"1.2.5.2.3. 산업별대출금(예금은행, 기업형태별)",Q,Y,한국은행
85,0000000040,131Y018,"1.2.5.2.4. 산업별대출금(예금은행, 기업규모별)",Q,Y,None
86,0000000040,132Y001,"1.2.5.2.5. 산업별대출금(예금은행, 지역별, 전산업)",Q,Y,None
87,0000000040,132Y003,"1.2.5.2.6. 산업별대출금(예금은행, 지역별, 용도별)",Q,Y,None
88,0000000038,0000000041,1.2.5.3. 비은행예금취급기관 산업별대출금,None,N,None
89,0000000041,131Y014,"1.2.5.3.1. 산업별대출금(비은행예금취급기관, 전산업)",Q,Y,None
90,0000000041,131Y015,"1.2.5.3.2. 산업별대출금(비은행예금취급기관, 용도별)",Q,Y,None
91,0000000020,0000000042,1.2.6. 기타 여수신 관련 통계,None,N,None
92,0000000042,104Y017,1.2.6.1. 예금은행 예금회전율,M,Y,None
93,0000000042,901Y123,1.2.6.2. 금융기관 점포/인원 현황,Q,Y,None
94,0000000042,0000000043,1.2.6.3. 은행대출금 연체율,None,N,None
95,0000000043,901Y054,1.2.6.3.1. 은행대출금 연체율(1일 이상),M,Y,은행연합회
96,0000000043,901Y124,1.2.6.3.2. 은행대출금 연체율(1개월 이상),M,Y,None
97,0000000042,901Y059,1.2.6.4. 보험계약실적,M,Y,생명보험협회(02-2262-6600)
98,0000000042,105Y001,1.2.6.5. 예금규모별 계좌수 및 금액,S,Y,한국은행
99,0000000001,0000000048,1.3. 금리,None,N,None
100,0000000048,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,D,Y,None
101,0000000048,0000000050,1.3.2. 시장금리,None,N,None
102,0000000050,817Y002,1.3.2.1. 시장금리(일별),D,Y,한국은행
103,0000000050,721Y001,"1.3.2.2. 시장금리(월,분기,년)",M,Y,한국은행
104,0000000048,0000000053,1.3.3. 예금은행 가중평균금리,None,N,None
105,0000000053,0000000054,1.3.3.1. 수신금리,None,N,None
106,0000000054,121Y002,1.3.3.1.1. 예금은행 수신금리(신규취급액 기준),M,Y,한국은행
107,0000000054,121Y013,1.3.3.1.2. 예금은행 수신금리(잔액 기준),M,Y,한국은행
108,0000000053,0000000055,1.3.3.2. 대출금리,None,N,None
109,0000000055,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),M,Y,한국은행
110,0000000055,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),M,Y,한국은행
111,0000000053,121Y008,1.3.3.3. 예금은행 금리수준별 여수신 비중(신규취급액 기준),M,Y,한국은행
112,0000000053,0000000057,1.3.3.4. 예금은행 고정 및 변동금리대출 비중,None,N,None
113,0000000057,121Y010,1.3.3.4.1. 예금은행 고정 및 변동금리대출 비중(신규취급액 기준),M,Y,None
114,0000000057,121Y011,1.3.3.4.2. 예금은행 고정 및 변동금리대출 비중(잔액 기준),M,Y,None
115,0000000048,0000000058,1.3.4. 비은행금융기관 가중평균금리,None,N,None
116,0000000058,121Y004,1.3.4.1. 비은행금융기관 수신금리(신규취급액 기준),M,Y,한국은행
117,0000000058,121Y007,1.3.4.2. 비은행금융기관 대출금리(신규취급액 기준),M,Y,한국은행
118,0000000001,0000000061,1.4. 한국은행 주요계정,None,N,None
119,0000000061,103Y002,1.4.1. 한국은행 주요계정(말잔),M,Y,한국은행
120,0000000061,871Y001,1.4.2. 화폐발행잔액,M,Y,한국은행
121,0000000061,0000000064,1.4.3. 예금은행 지급준비액,None,N,None
122,0000000064,814Y001,"1.4.3.1. 예금은행 지급준비액(신기준, 평잔)",M,Y,한국은행
123,0000000064,814Y002,"1.4.3.2. 예금은행 지급준비액(구기준, 평잔)",SM,Y,한국은행
124,0000000061,641Y001,1.4.4. 한국은행 원화대출금,M,Y,None
125,0000000001,0000000397,1.5. 주식/채권/재정,None,N,None
126,0000000397,0000000398,1.5.1. 주식거래/주가지수,None,N,None
127,0000000398,802Y001,1.5.1.1. 주식시장(일),D,Y,한국거래소(051-662-2000)
128,0000000398,901Y014,"1.5.1.2. 주식시장(월,년)",M,Y,한국거래소(051-662-2000)
129,0000000398,901Y055,1.5.1.3. 투자자별 주식거래,M,Y,한국거래소(051-662-2000)
130,0000000398,901Y056,1.5.1.4. 증시주변자금동향,M,Y,금융투자협회(02-2003-9000)
131,0000000398,901Y057,1.5.1.5. 주가지수선물거래,M,Y,한국거래소(051-662-2000)
132,0000000398,901Y058,1.5.1.6. 주가지수옵션거래,M,Y,한국거래소(051-662-2000)
133,0000000397,0000000957,1.5.2. 채권거래,None,N,None
134,0000000957,901Y015,1.5.2.1. 채권종류별 거래,M,Y,한국거래소(051-662-2000)
135,0000000957,901Y120,1.5.2.2. 채권시장별 거래,M,Y,None
136,0000000397,191Y001,1.5.3. 주요 국공채 발행액/잔액,M,Y,None
137,0000000397,0000000399,1.5.4. 재정,None,N,None
138,0000000399,901Y013,1.5.4.1. 통합재정수지,M,Y,기획재정부(044-215-2114)
139,0000000399,901Y081,1.5.4.2. 조세징수액,A,Y,기획재정부(044-215-2114)
140,0000000001,0000001000,1.6. 차주별 가계부채,None,N,None
141,0000001000,0000001001,1.6.1. 차주당 금액 기준,None,N,None
142,0000001001,0000001003,1.6.1.1. 신규취급액,None,N,None
143,0000001003,181Y001,1.6.1.1.1. 차주당 가계대출 신규취급액,Q,Y,None
144,0000001003,0000001007,1.6.1.1.2. 차주당 가계대출 신규취급액 (교차항목),None,N,None
145,0000001007,181Y003,1.6.1.1.2.1. 연령별 지역별,Q,Y,None
146,0000001007,181Y005,1.6.1.1.2.2. 연령별 업권별,Q,Y,None
147,0000001007,181Y007,1.6.1.1.2.3. 연령별 상품별,Q,Y,None
148,0000001007,181Y009,1.6.1.1.2.4. 상품별 업권별,Q,Y,None
149,0000001003,181Y011,1.6.1.1.3. 차주당 주택담보대출 신규취급액,Q,Y,None
150,0000001001,0000001004,1.6.1.2. 잔액,None,N,None
151,0000001004,181Y002,1.6.1.2.1. 차주당 가계대출 잔액,Q,Y,None
152,0000001004,0000001008,1.6.1.2.2. 차주당 가계대출 잔액 (교차항목),None,N,None
153,0000001008,181Y004,1.6.1.2.2.1. 연령별 지역별,Q,Y,None
154,0000001008,181Y006,1.6.1.2.2.2. 연령별 업권별,Q,Y,None
155,0000001008,181Y008,1.6.1.2.2.3. 연령별 상품별,Q,Y,None
156,0000001008,181Y010,1.6.1.2.2.4. 상품별 업권별,Q,Y,None
157,0000001004,181Y012,1.6.1.2.3. 차주당 주택담보대출 잔액,Q,Y,None
158,0000001000,0000001002,1.6.2. 금액 비중 기준,None,N,None
159,0000001002,0000001005,1.6.2.1. 신규취급액,None,N,None
160,0000001005,181Y013,1.6.2.1.1. 가계대출 신규취급액 비중,Q,Y,None
161,0000001005,181Y015,1.6.2.1.2. 주택담보대출 신규취급액 비중,Q,Y,None
162,0000001002,0000001006,1.6.2.2. 잔액,None,N,None
163,0000001006,181Y016,1.6.2.2.1. 가계대출 잔액 비중,Q,Y,None
164,0000001006,181Y014,1.6.2.2.2. 주택담보대출 잔액 비중,Q,Y,None
165,0000000001,0000000002,1.7. 통화/유동성(구지표),None,N,None
166,0000000002,0000000003,1.7.1. 본원통화,None,N,None
167,0000000003,0000000004,1.7.1.1. 본원통화 구성내역,None,N,None
168,0000000004,102Y104,"1.7.1.1.1. 본원통화 구성내역(평잔, 계절조정계열)",M,Y,None
169,0000000004,102Y102,"1.7.1.1.2. 본원통화 구성내역(평잔, 원계열)",M,Y,None
170,0000000004,102Y103,"1.7.1.1.3. 본원통화 구성내역(말잔, 계절조정계열)",M,Y,None
171,0000000004,102Y101,"1.7.1.1.4. 본원통화 구성내역(말잔, 원계열)",M,Y,None
172,0000000002,0000000005,1.7.2. M1(협의통화),None,N,None
173,0000000005,0000000006,1.7.2.1. M1(협의통화) 상품별 구성내역,None,N,None
174,0000000006,101Y018,"1.7.2.1.1. M1 상품별 구성내역(평잔, 계절조정계열)",M,Y,None
175,0000000006,101Y019,"1.7.2.1.2. M1 상품별 구성내역(평잔, 원계열)",M,Y,None
176,0000000006,101Y016,"1.7.2.1.3. M1 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
177,0000000006,101Y017,"1.7.2.1.4. M1 상품별 구성내역(말잔, 원계열)",M,Y,None
178,0000000002,0000000007,1.7.3. M2(광의통화),None,N,None
179,0000000007,0000000008,1.7.3.1. M2(광의통화) 상품별 구성내역,None,N,None
180,0000000008,101Y003,"1.7.3.1.1. M2 상품별 구성내역(평잔, 계절조정계열)",M,Y,None
181,0000000008,101Y004,"1.7.3.1.2. M2 상품별 구성내역(평잔, 원계열)",M,Y,None
182,0000000008,101Y001,"1.7.3.1.3. M2 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
183,0000000008,101Y002,"1.7.3.1.4. M2 상품별 구성내역(말잔, 원계열)",M,Y,None
184,0000000007,0000000009,1.7.3.2. M2(광의통화) 경제주체별 보유현황,None,N,None
185,0000000009,101Y006,"1.7.3.2.1. M2 경제주체별 보유현황(평잔, 계절조정계열)",M,Y,None
186,0000000009,101Y015,"1.7.3.2.2. M2 경제주체별 보유현황(평잔, 원계열)",M,Y,None
187,0000000009,101Y005,"1.7.3.2.3. M2 경제주체별 보유현황(말잔, 계절조정계열)",M,Y,None
188,0000000009,101Y014,"1.7.3.2.4. M2 경제주체별 보유현황(말잔, 원계열)",M,Y,None
189,0000000007,0000000010,1.7.3.3. M2 기관별 구성내역,None,N,None
190,0000000010,101Y008,1.7.3.3.1. M2 기관별구성내역(평잔),M,Y,None
191,0000000010,101Y007,1.7.3.3.2. M2 기관별구성내역(말잔),M,Y,None
192,0000000002,0000000012,1.7.4. Lf(금융기관 유동성) 관련통계,None,N,None
193,0000000012,0000000013,1.7.4.1. Lf(금융기관 유동성) 상품별 구성내역,None,N,None
194,0000000013,111Y003,"1.7.4.1.1. Lf 상품별 구성내역(평잔, 계절조정계열)",M,Y,None
195,0000000013,111Y004,"1.7.4.1.2. Lf 상품별 구성내역(평잔, 원계열)",M,Y,None
196,0000000013,111Y001,"1.7.4.1.3. Lf 상품별 구성내역(말잔, 계절조정계열)",M,Y,None
197,0000000013,111Y002,"1.7.4.1.4. Lf 상품별 구성내역(말잔, 원계열)",M,Y,None
198,0000000002,0000000015,1.7.5. L(광의유동성) 구성내역,None,N,None
199,0000000015,112Y001,"1.7.5.1. L(광의유동성) 구성내역(말잔, 계절조정계열)",M,Y,None
200,0000000015,112Y002,"1.7.5.2. L(광의유동성) 구성내역(말잔, 원계열)",M,Y,None
201,0000000002,0000000017,1.7.6. 예금취급기관 개관표,None,N,None
202,0000000017,101Y009,1.7.6.1. 예금취급기관 개관표(말잔),M,Y,한국은행
203,0000000017,101Y010,1.7.6.2. 중앙은행 개관표(말잔),M,Y,한국은행
204,0000000017,101Y011,1.7.6.3. 기타예금취급기관 개관표(말잔),M,Y,한국은행
205,*,0000000066,2. 국민계정,None,N,None
206,0000000066,0000000910,2.1. 국민소득통계(2020년 기준년),None,N,None
207,0000000910,0000000911,2.1.1. 주요지표,None,N,None
208,0000000911,200Y101,2.1.1.1. 주요지표(연간지표),A,Y,None
209,0000000911,200Y102,2.1.1.2. 주요지표(분기지표),Q,Y,None
210,0000000910,0000000912,"2.1.2. 생산, 지출 및 분배 GDP, GDP 디플레이터",None,N,None
211,0000000912,0000000913,2.1.2.1. 경제활동별 GDP 및 GNI,None,N,None
212,0000000913,200Y103,"2.1.2.1.1. 경제활동별 GDP 및 GNI(계절조정, 명목, 분기)",Q,Y,None
213,0000000913,200Y104,"2.1.2.1.2. 경제활동별 GDP 및 GNI(계절조정, 실질, 분기)",Q,Y,None
214,0000000913,200Y105,"2.1.2.1.3. 경제활동별 GDP 및 GNI(원계열, 명목, 분기 및 연간)",Q,Y,None
215,0000000913,200Y106,"2.1.2.1.4. 경제활동별 GDP 및 GNI(원계열, 실질, 분기 및 연간)",Q,Y,None
216,0000000912,0000000914,2.1.2.2. 국내총생산에 대한 지출,None,N,None
217,0000000914,200Y107,"2.1.2.2.1. 국내총생산에 대한 지출(계절조정, 명목, 분기)",Q,Y,None
218,0000000914,200Y108,"2.1.2.2.2. 국내총생산에 대한 지출(계절조정, 실질, 분기)",Q,Y,None
219,0000000914,200Y109,"2.1.2.2.3. 국내총생산에 대한 지출(원계열, 명목, 분기 및 연간)",Q,Y,None
220,0000000914,200Y110,"2.1.2.2.4. 국내총생산에 대한 지출(원계열, 실질, 분기 및 연간)",Q,Y,None
221,0000000912,0000000936,2.1.2.3. 부가가치 항목별 명목 GDP,None,N,None
222,0000000936,200Y160,"2.1.2.3.1. 부가가치 항목별 명목 GDP(계절조정, 명목, 분기)",Q,Y,None
223,0000000936,200Y161,"2.1.2.3.2. 부가가치 항목별 명목 GDP(원계열, 명목, 분기 및 연간)",Q,Y,None
224,0000000912,0000000915,2.1.2.4. GDP 디플레이터,None,N,None
225,0000000915,200Y111,2.1.2.4.1. 경제활동별 국내총생산 디플레이터(분기 및 연간),Q,Y,None
226,0000000915,200Y112,2.1.2.4.2. 국내총생산에 대한 지출 디플레이터(분기 및 연간),Q,Y,None
227,0000000910,0000000916,2.1.3. 종합계정,None,N,None
228,0000000916,0000000917,2.1.3.1. 국내총생산과 지출,None,N,None
229,0000000917,200Y113,"2.1.3.1.1. 국내총생산과 지출(명목, 연간)",A,Y,None
230,0000000917,200Y114,"2.1.3.1.2. 경제활동별 국내총부가가치와 요소소득(명목, 연간)",A,Y,None
231,0000000916,0000000918,2.1.3.2. 국민처분가능소득과 처분,None,N,None
232,0000000918,200Y115,"2.1.3.2.1. 국민처분가능소득과 처분(명목, 연간)",A,Y,None
233,0000000918,200Y116,"2.1.3.2.2. 국민소득과 부문별 국민처분가능소득(명목, 연간)",A,Y,None
234,0000000916,0000000919,2.1.3.3. 자본거래,None,N,None
235,0000000919,200Y117,"2.1.3.3.1. 자본거래(명목, 연간)",A,Y,None
236,0000000916,0000000920,2.1.3.4. 국외거래,None,N,None
237,0000000920,200Y118,"2.1.3.4.1. 경상거래(명목, 연간)",A,Y,None
238,0000000920,200Y119,"2.1.3.4.2. 자본거래(명목, 연간)",A,Y,None
239,0000000910,0000000921,2.1.4. 제도부문별 계정,None,N,None
240,0000000921,200Y120,"2.1.4.1. 제도부문별 생산계정(명목, 연간)",A,Y,None
241,0000000921,200Y121,"2.1.4.2. 제도부문별 소득계정(명목, 연간)",A,Y,None
242,0000000921,200Y162,"2.1.4.3. 제도부문별 소득계정(명목, 분기)",Q,Y,None
243,0000000921,200Y122,"2.1.4.4. 제도부문별 자본계정(명목, 연간)",A,Y,None
244,0000000910,0000000922,2.1.5. GDP에 대한 성장기여도,None,N,None
245,0000000922,200Y123,"2.1.5.1. 경제활동별 성장기여도(계절조정, 실질, 분기)",Q,Y,None
246,0000000922,200Y124,"2.1.5.2. 경제활동별 성장기여도(원계열, 실질, 분기 및 연간)",Q,Y,None
247,0000000922,200Y125,"2.1.5.3. 지출항목별 성장기여도(계절조정, 실질, 분기)",Q,Y,None
248,0000000922,200Y126,"2.1.5.4. 지출항목별 성장기여도(원계열, 실질, 분기 및 연간)",Q,Y,None
249,0000000910,0000000923,2.1.6. 총자본형성,None,N,None
250,0000000923,0000000924,2.1.6.1. 자본재형태별 총자본형성,None,N,None
251,0000000924,200Y127,"2.1.6.1.1. 자본재형태별 총자본형성(계절조정, 명목, 분기)",Q,Y,None
252,0000000924,200Y128,"2.1.6.1.2. 자본재형태별 총자본형성(계절조정, 실질, 분기)",Q,Y,None
253,0000000924,200Y129,"2.1.6.1.3. 자본재형태별 총자본형성(원계열, 명목, 분기 및 연간)",Q,Y,None
254,0000000924,200Y130,"2.1.6.1.4. 자본재형태별 총자본형성(원계열, 실질, 분기 및 연간)",Q,Y,None
255,0000000923,0000000925,2.1.6.2. 주체별 총자본형성,None,N,None
256,0000000925,200Y131,"2.1.6.2.1. 주체별 총자본형성(원계열, 명목, 분기 및 연간)",Q,Y,None
257,0000000925,200Y132,"2.1.6.2.2. 주체별 총자본형성(원계열, 실질, 분기 및 연간)",Q,Y,None
258,0000000925,200Y133,"2.1.6.2.3. 주체별 총고정자본형성(계절조정, 명목, 분기)",Q,Y,None
259,0000000925,200Y134,"2.1.6.2.4. 주체별 총고정자본형성(계절조정, 실질, 분기)",Q,Y,None
260,0000000923,0000000926,2.1.6.3. 경제활동별 총고정자본형성,None,N,None
261,0000000926,200Y135,"2.1.6.3.1. 경제활동별 총고정자본형성(명목, 연간)",A,Y,None
262,0000000926,200Y136,"2.1.6.3.2. 경제활동별 총고정자본형성(실질, 연간)",A,Y,None
263,0000000926,200Y137,"2.1.6.3.3. 경제활동별 자본재형태별 총고정자본형성(명목, 연간)",A,Y,None
264,0000000923,0000000927,2.1.6.4. 경제활동별 설비투자,None,N,None
265,0000000927,200Y138,"2.1.6.4.1. 경제활동별 설비투자(명목, 연간)",A,Y,None
266,0000000927,200Y139,"2.1.6.4.2. 경제활동별 설비투자(실질, 연간)",A,Y,None
267,0000000910,0000000928,2.1.7. 민간최종소비지출,None,N,None
268,0000000928,0000000929,2.1.7.1. 가계의 목적별 최종소비지출,None,N,None
269,0000000929,200Y140,"2.1.7.1.1. 가계의 목적별 최종소비지출(계절조정, 명목, 분기)",Q,Y,None
270,0000000929,200Y141,"2.1.7.1.2. 가계의 목적별 최종소비지출(계절조정, 실질, 분기)",Q,Y,None
271,0000000929,200Y142,"2.1.7.1.3. 가계의 목적별 최종소비지출(원계열, 명목, 분기 및 연간)",Q,Y,None
272,0000000929,200Y143,"2.1.7.1.4. 가계의 목적별 최종소비지출(원계열, 실질, 분기 및 연간)",Q,Y,None
273,0000000928,0000000930,2.1.7.2. 가계의 형태별 최종소비지출,None,N,None
274,0000000930,200Y144,"2.1.7.2.1. 가계의 형태별 최종소비지출(계절조정, 명목, 분기)",Q,Y,None
275,0000000930,200Y145,"2.1.7.2.2. 가계의 형태별 최종소비지출(계절조정, 실질, 분기)",Q,Y,None
276,0000000930,200Y146,"2.1.7.2.3. 가계의 형태별 최종소비지출(원계열, 명목, 분기 및 연간)",Q,Y,None
277,0000000930,200Y147,"2.1.7.2.4. 가계의 형태별 최종소비지출(원계열, 실질, 분기 및 연간)",Q,Y,None
278,0000000928,0000000931,2.1.7.3. 가계에 봉사하는 비영리단체의 목적별 최종소비지출,None,N,None
279,0000000931,200Y148,"2.1.7.3.1. 가계에 봉사하는 비영리단체의 목적별 최종소비지출(원계열, 명목,...",Q,Y,None
280,0000000931,200Y149,"2.1.7.3.2. 가계에 봉사하는 비영리단체의 목적별 최종소비지출(원계열, 실질,...",Q,Y,None
281,0000000910,0000000932,2.1.8. 일반정부 및 공공부문계정,None,N,None
282,0000000932,200Y151,"2.1.8.1. 일반정부의 부문별 기능별 최종소비지출(명목, 연간)",A,Y,None
283,0000000932,200Y152,"2.1.8.2. 일반정부의 부문별 기능별 총지출 (명목, 연간)",A,Y,None
284,0000000932,200Y153,"2.1.8.3. 일반정부의 부문별 총수입, 총지출, 저축투자차액(명목, 연간)",A,Y,None
285,0000000932,200Y154,"2.1.8.4. 공공부문의 부문별 총수입, 총지출, 저축투자차액(명목, 연간)",A,Y,None
286,0000000910,0000000933,2.1.9. 총저축과 총투자,None,N,None
287,0000000933,200Y155,"2.1.9.1. 총저축과 총투자(계절조정, 명목, 분기)",Q,Y,None
288,0000000933,200Y156,"2.1.9.2. 총저축과 총투자(원계열, 명목, 분기 및 연간)",Q,Y,None
289,0000000910,0000000934,2.1.10. 정보통신 부가가치 및 최종수요,None,N,None
290,0000000934,200Y157,"2.1.10.1. 정보통신산업(계절조정, 실질, 분기)",Q,Y,None
291,0000000934,200Y158,"2.1.10.2. 정보통신산업(원계열, 실질, 분기 및 연간)",Q,Y,None
292,0000000910,0000000935,2.1.11. 가계분배계정(실험적 통계),None,N,None
293,0000000935,200Y159,"2.1.11.1. 가계분배계정(명목, 연간)",A,Y,None
294,0000000066,0000000110,2.2. 산업연관표,None,N,None
295,0000000110,0000000901,2.2.1. 2020년 실측표 기준,None,N,None
296,0000000901,0000000902,2.2.1.1. 파일 다운로드,None,N,None
297,0000000902,271Y102,2023 연장표,A,Y,한국은행
298,0000000902,271Y103,2022 연장표,A,Y,한국은행
299,0000000902,271Y104,2021 연장표,A,Y,한국은행
300,0000000902,271Y105,2020 실측표,A,Y,한국은행
301,0000000902,271Y106,2020 지역표,A,Y,None
302,0000000902,271Y108,2020 부문분류표,A,Y,None
303,0000000902,271Y109,고용표,A,Y,None
304,0000000901,0000000903,2.2.1.2. 데이터,None,N,None
305,0000000903,271Y110,"2.2.1.2.1. 투입산출표 총거래표(생산자가격, 대분류)",A,Y,None
306,0000000903,271Y111,"2.2.1.2.2. 투입산출표 총투입계수표(생산자가격, 대분류)",A,Y,None
307,0000000903,271Y112,"2.2.1.2.3. 투입산출표 생산유발계수표(생산자가격, 대분류)",A,Y,None
308,0000000903,271Y113,"2.2.1.2.4. 투입산출표 수입유발계수표(생산자가격, 대분류)",A,Y,None
309,0000000903,271Y114,"2.2.1.2.5. 투입산출표 부가가치유발계수표(생산자가격, 대분류)",A,Y,None
310,0000000903,271Y115,"2.2.1.2.6. 투입산출표 취업유발계수표(생산자가격, 대분류)",A,Y,None
311,0000000903,271Y116,"2.2.1.2.7. 투입산출표 고용유발계수표(생산자가격, 대분류)",A,Y,None
312,0000000903,271Y120,"2.2.1.2.8. 투입산출표 총거래표(생산자가격, 중분류)",A,Y,None
313,0000000903,271Y121,"2.2.1.2.9. 투입산출표 총투입계수표(생산자가격, 중분류)",A,Y,None
314,0000000903,271Y122,"2.2.1.2.10. 투입산출표 생산유발계수표(생산자가격, 중분류)",A,Y,None
315,0000000903,271Y123,"2.2.1.2.11. 투입산출표 수입유발계수표(생산자가격, 중분류)",A,Y,None
316,0000000903,271Y124,"2.2.1.2.12. 투입산출표 부가가치유발계수표(생산자가격, 중분류)",A,Y,None
317,0000000903,271Y125,"2.2.1.2.13. 투입산출표 취업유발계수표(생산자가격, 중분류)",A,Y,None
318,0000000903,271Y126,"2.2.1.2.14. 투입산출표 고용유발계수표(생산자가격, 중분류)",A,Y,None
319,0000000110,0000000531,2.2.2. 2015년 실측표 기준,None,N,None
320,0000000531,0000000534,2.2.2.1. 파일 다운로드,None,N,None
321,0000000534,271Y001,2019 연장표,A,Y,한국은행
322,0000000534,271Y002,2018 연장표,A,Y,한국은행
323,0000000534,271Y003,2017 연장표,A,Y,한국은행